### ISSUE TITLE
LICENSE? 

### ISSUE THREAD

**Issue by R-Walmsley** [activityMonitoring/wearable-teaching#23]
License is currently MIT, when most of our public repos use a specially-developed Academic Use License. Is that intentional?

**Comment by aidendoherty** [comment]
Great spot. @chanshing can you update this license please?

**Comment by aidendoherty** [comment]
Hi @chanshing - a reminder to request you update the licence on this repo.
Many thanks

**Comment by chanshing** [comment]
Thanks @aidendoherty sorry for the slow response. It's fixed now fcacfb5a566450d3b18717f097ecbecf81e31278
