### ISSUE TITLE
create a brief prac4-activityRecognition.md file

### ISSUE THREAD

**Issue by aidendoherty** [activityMonitoring/wearable-teaching#3]
Shing - can you also create a brief prac4-activityRecognition.md file? Or figure out how to turn the notebook into a PDF that can be uploaded to CANVAS to guide the students on what they should do (and how they can get the capture-24 dataset)

**Comment by chanshing** [comment]
I added instructions to obtain the required files/datasets to run the notebook in https://github.com/activityMonitoring/wearable-teaching/commit/7dd00bd0d82dc411a1be21c0a6b99c1af129cf2c
I think this should be all they need but let me know otherwise :D
