### ISSUE TITLE
Add documentation to practical 1 on how to setup accelerometer

### ISSUE THREAD

**Issue by aidendoherty** [activityMonitoring/wearable-teaching#4]
@angerhang If the students do have chromebooks, they can use the OMGUI tool to setup the devices - see https://github.com/digitalinteraction/openmovement/wiki/AX3-GUI 

For those with OSX, this webservice seems to work (sometimes) - https://config.openmovement.dev/

**Comment by angerhang** [comment]
Added via https://github.com/activityMonitoring/wearable-teaching/commit/817b5784b7468bfa9617b6e2c5568cec0caf46a9 and https://github.com/activityMonitoring/wearable-teaching/commit/795b05729e618cacc934c06fafc4a89a2bb7110e
