### ISSUE TITLE
Sample data for future reference

### ISSUE THREAD

**Issue by angerhang** [activityMonitoring/wearable-teaching#5]
@aidendoherty  as this module is coming to an end, do you think it would a good idea to keep the data that I recorded this year stored somewhere indefinitely just in case that people will still need this in the future and we won't have to repeat wearing the device when helping out with the practical? I would be fine to share the data with others and leave it open.

**Comment by aidendoherty** [comment]
Hi @angerhang - this would be really helpful if possible. Perhaps we could store this under a 'teaching' folder on the rescomp/bmrc system?

**Comment by angerhang** [comment]
Done via https://github.com/activityMonitoring/wearable-teaching/commit/e9b4e9628e28ec772bf9fd2bb5484cd0b3daa6c2, thus closing.
